import mongoose, { Schema, model, models, Document } from "mongoose";
import { Pastor, ClergyType, MaritalStatus } from "@/types/entities";

interface PastorDocument extends Omit<Pastor, "id" | "date_of_birth" | "date_of_appointment" | "church">, Document {
  date_of_birth: Date;
  date_of_appointment: Date;
  church: mongoose.Types.ObjectId;
}

const PastorSchema = new Schema<PastorDocument>(
  {
    first_name: {
      type: String,
      required: [true, "Please provide a first name"],
      maxlength: [50, "First name cannot be more than 50 characters"],
    },
    middle_name: {
      type: String,
      required: false,
      maxlength: [50, "Middle name cannot be more than 50 characters"],
    },
    last_name: {
      type: String,
      required: [true, "Please provide a last name"],
      maxlength: [50, "Last name cannot be more than 50 characters"],
    },
    date_of_birth: {
      type: Date,
      required: false,
    },
    date_of_appointment: {
      type: Date,
      required: false,
    },
    profile_image: {
      type: String,
      required: false,
    },
    clergy_type: {
      type: [String],
      enum: ["Bishop", "Mother", "Sister", "Reverend", "Pastor", "Governor"],
      required: [true, "Please select at least one title"],
      validate: {
        validator: function (v: string[]) {
          // Require at least one title
          if (!v || v.length === 0) return false;
          // Allow maximum of 2 titles
          if (v.length > 2) return false;
          // If there are 2 titles, one must be Governor
          if (v.length === 2 && !v.includes("Governor")) return false;
          return true;
        },
        message: "A pastor must have at least one title (maximum of 2), and if there are 2, one must be Governor",
      },
    },
    marital_status: {
      type: String,
      enum: ["Single", "Married", "Divorced", "Widowed"],
      required: false,
    },
    church: {
      type: Schema.Types.ObjectId,
      ref: "Church",
      required: false,
      default: null,
    },
    gender: {
      type: String,
      enum: ["Male", "Female"],
      required: false,
    },
    council: {
      type: String,
      enum: [
        "Philippians",
        "Galatians",
        "Colossians",
        "2 Corinthians",
        "Anagkazo",
        "Ephesians",
        "Signs and Wonders HGE",
        "Greater Love Club",
        "GLGC",
        "Film Stars",
        "Dancing Stars",
        "Praise and Worship",
        "Eels on wheels",
        "Spiders",
        "Doves",
        "Lizardos",
        "Butterflies",
        "Kangaroos",
        "Impalas",
        "Unicorns",
        "Gazelles",
        "Camels",
        "Eagles",
        "Lions",
        "Dolphins",
        "Actors Ministry",
        "Props Ministry",
        "Costume ministry",
        "Make up",
        "Protocol",
        "Script writers",
        "Social media",
        "Technical",
        "Love theatre company",
        "Many Are Called",
        "Love is Large",
        "Peace and Love",
        "True Love",
        "Love Never Fails",
        "Abundant Love",
        "Steadfast Love",
        "Perfect Love",
        "Unfeigned Love",
        "Love Is Patient",
        "Everlasting Love",
        "God So Loved",
        "Praise Stars",
        "Worship Stars",
        "N/A",
        "Backstage Hostesses",
        "Backstage Hosts",
        "Engedi Food Team",
        "Mood Changing Food Team",
        "Marriage Counseling",
        "Sheep seeking September",
        "Sheep seeking October",
        "Sheep seeking November",
        "Sheep seeking December",
        "Sheep seeking January",
        "Sheep seeking February",
        "Sheep seeking March",
        "Sheep seeking April",
        "Sheep seeking May",
        "Sheep seeking June",
        "Sheep seeking July",
        "Sheep seeking August",
        "School of Solid Foundation",
        "School of Victorious Living",
        "School of Evangelism",
        "School of the Word",
        "School of Apologetics",
        "Addictions and substance abuse Counsellors",
        "Grief and Trauma Counsellors",
        "Relationship and love related issues Counsellors",
        "Career and financial management Counsellors",
        "Business Community",
        "Music mixers",
        "Salvation corner ushers",
        "Podcast corner ushers",
        "Balcony ushers",
        "Left wing ushers",
        "Right wing ushers",
        "Middle ground ushers",
        "Photography Team",
        "Vox Team",
        "Video Clip Cutters Team",
        "YouTube & Graphics Team",
        "X Team",
        "TikTok & Snapchat Team",
        "Videography team",
        "Meta Team",
        "FLOC Production and editing Team",
        "Clap nighters",
        "Sunday intercessors",
        "Soul winning intercessors",
        "Testimony Maestros",
        "Mood changing Campus control",
        "External Campus control",
        "Cross Car Park Campus control",
        "Office block Car Park Campus control",
        "Revival street Campus control",
        "Lord's Tower- Praise and Worship",
        "Lord's Tower- Preaching and solo team",
        "Lord's Tower- Film stars",
        "Lord's Tower- Choir",
        "Lord's Tower- Dance",
        "Choir Telepastors",
        "Dancing stars Telepastors",
        "Film stars Telepastors",
        "Basonta Telepastors",
        "Philippians Telepastors",
        "Galatians Telepastors",
        "Ephesians Telepastors",
        "Anagkazo Telepastors",
        "Hostesses of the Offices",
        "Hostesses of the First timers",
        "Hostesses of the Greater lovers & Special Visitors",
        "Balcony Security",
        "Stage Security",
        "Ground Security",
        "I - church",
        "J - Church",
        "K - Church",
        "B - Church",
        "Y - Church",
        "Lovelets Check in",
        "Smiles on arrival airport stars",
        "First Offering airport stars",
        "Second offering airport stars",
        "Bus welcomers airport stars",
        "Car welcomers airport stars",
        "Car confirmers",
        "Bus confirmers",
        "Payments",
        "Treasurers",
        "Fragrance",
        "Governors lounge",
        "The Lord's garden",
        "HGE Telepastors",
        "HGE Understanding campaign",
        "HGE Sheep seeking",
        "HGE Airport Stars",
        "HGE Intimate counseling",
        "HGE Lord's tower",
        "HGE Ushers",
        "HGE Hostesses",
        "HGE Hearing and seeing",
        "None",
      ],
      required: [true, "Please select a council"],
    },
    area: {
      type: String,
      enum: [
        "HGE Area 1",
        "HGE Area 2",
        "HGE Area 3",
        "HGE Area 4",
        "Experience Area 1",
        "Experience Area 2",
        "Experience Area 3",
        "Experience Area 4",
        "None",
      ],
      required: [true, "Please select an area"],
    },
    occupation: {
      type: String,
      required: false,
    },
    country: {
      type: String,
      required: false,
    },
    email: {
      type: String,
      required: false,
      lowercase: true,
      trim: true,
    },
    contact_number: {
      type: String,
      required: false,
    },
    status: {
      type: String,
      enum: ["Active", "Inactive"],
      default: "Active",
      required: false,
    },
    function: {
      type: [String],
      enum: ["Governor", "Overseer"],
      required: [true, "Please select at least one function"],
      set: (v: string | string[]) => {
        if (!v) return v;
        const arr = Array.isArray(v) ? v : [v];
        return [...new Set(arr.filter(Boolean))];
      },
      validate: {
        validator: function (v: string[]) {
          if (!Array.isArray(v)) return false;
          if (v.length === 0 || v.length > 2) return false;
          return v.every((value) => ["Governor", "Overseer"].includes(value));
        },
        message: "A pastor must have 1-2 functions and they must be Governor and/or Overseer",
      },
    },
  },
  {
    timestamps: true,
  }
);

// Add compound index for duplicate checking
PastorSchema.index({ first_name: 1, last_name: 1, date_of_birth: 1 });

export default models.Pastor || model<PastorDocument>("Pastor", PastorSchema);
